### ISSUE TITLE
Cargo machete PR breaks build

### ISSUE THREAD

**Issue by DarthB** [blackportal-ai/nebula#8]
Cargo machete thinks the project dependencies for prost and strum are not needed.

Without them there are several (100+) trait related compile errors.
This is a [know issue](https://github.com/hyperium/tonic/issues/1858) in tonic 

Workaround: Add the following lines to `nebula_common/Cargo.toml`
```toml
[dependencies]
# ...
prost.workspace = true
strum.workspace = true
```
